pydrive/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('trash.urls')),
]

trash/urls.py
from django.conf.urls import url
from trash import views

urlpatterns = [
    url(r'^create/$', views.CreateTrashView.as_view(), name='create_trash'),
    url(r'^$', views.trash_list, name='trash_list'),
    url(r'^content/(?P<trash_name>\w+)/$', views.trash_content, name='trash_content'),
    url(r'^remove_ajax/$', views.remove_ajax, name='remove_files'),
    url(r'^remove_form/$', views.RemoveFormView.as_view(), name='remove'),
    url(r'^recover_form/$', views.RecoveryFormView.as_view(), name='recover'),
    url(r'^recover_ajax/$', views.recover_ajax, name='recover_files'),
    url(r'^content_ajax/$', views.trash_content_ajax, name='trash_content_ajax'),
    url(r'^tasks/$', views.tasks, name='tasks'),
]

trash/models.py
from __future__ import unicode_literals
from django.db import models
from varm.trash.trash import Trash, DEFAULT_FILES_LIMIT, DEFAULT_SIZE_LIMIT
from os.path import join, expanduser
from multiprocessing.pool import ThreadPool


class TrashModel(models.Model):
    """
    TrashModel store settings for instance of pyrm.trash.trash.Trash class
    Fields:
        name - name of pyrm.trash.trash.Trash
        files_limit - files_limit of pyrm.trash.trash.Trash
        size_limit - size_limit of pyrm.trash.trash.Trash
        time_creation - time of creation TrashModel instance
    """

    ROOT_PATH = expanduser('~')

    name = models.CharField(max_length=50, unique=True)
    files_limit = models.PositiveIntegerField(default=DEFAULT_FILES_LIMIT)
    size_limit = models.PositiveIntegerField(default=DEFAULT_SIZE_LIMIT)
    time_creation = models.DateTimeField(auto_now=True)

    def remove(self, filename):
        """
        Remove file from trash by filename
        :param filename: name file, which will removed
        :return: None
        """
        removed_files = self.instance.remove(filename)
        status = TrashModelTask.STATUS_SUCCESS if removed_files \
            else TrashModelTask.STATUS_FAIL

        self.trashmodeltask_set.create(
            status=status,
            operation=TrashModelTask.OPERATION_REMOVE,
            filename=filename,
        )

    def recover(self, filename):
        """
        Recover file from trash by filename
        :param filename: name of file which will removed
        :return: None
        """
        recovered_files = self.instance.recover(filename)
        status = TrashModelTask.STATUS_SUCCESS if recovered_files \
            else TrashModelTask.STATUS_FAIL

        self.trashmodeltask_set.create(
            status=status,
            operation=TrashModelTask.OPERATION_RECOVER,
            filename=filename,
        )

    def remove_many(self, file_list):
        """
        Remove list of files. Each file remove in new thread
        :param file_list: list of file which will remov
        :return: None
        """
        pool = ThreadPool()
        for file in file_list:
            pool.apply_async(self.remove, args=(file,))

        pool.close()
        pool.join()

    def recover_many(self, file_list):
        """
        Recover list of files. Each file recover in new thread
        :param file_list: list of file which will recover
        :return: None
        """
        pool = ThreadPool()
        for file in file_list:
            pool.apply_async(self.recover, args=(file,))

        pool.close()
        pool.join()

    def content(self):
        """
        Trash content
        :return: list of trash files
        """
        return self.instance.list()

    @property
    def instance(self):
        """
        Trash instance property
        :return: pyrm.trash.trash.Trash instance with model settings
        """
        return Trash(
            join(self.ROOT_PATH, self.name),
            self.files_limit,
            self.size_limit
        )

    def __str__(self):
        return self.name


class TrashModelTask(models.Model):
    """
    Store detail info for each task of trash model.
    Fields:
        trash - target of task
        status - store trash task status based on STATUS choices
        operation - store trash task operation
        filename - target of task based on OPERATIONS choices
    """
    STATUS_SUCCESS = 0
    STATUS_FAIL = 1

    STATUS = (
        (STATUS_SUCCESS, 'Success'),
        (STATUS_FAIL, 'Fail'),
    )

    OPERATION_REMOVE = 0
    OPERATION_RECOVER = 1

    OPERATIONS = (
        (OPERATION_REMOVE, 'Remove'),
        (OPERATION_RECOVER, 'Recover'),
    )

    trash = models.ForeignKey(TrashModel, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS)
    operation = models.IntegerField(choices=OPERATIONS)
    filename = models.FilePathField()

    def __str__(self):
        return 'Query {0}'.format(self.pk)

trash/forms.py
from django import forms
from trash.models import TrashModel


class CreateTrashForm(forms.ModelForm):
    """
    Model-based form for create trash.
    """
    class Meta:
        model = TrashModel
        fields = ['name', 'files_limit', 'size_limit']


class TaskForm(forms.Form):
    """
    Task form.
    """
    trash = forms.CharField(max_length=50)
    file = forms.CharField(max_length=50)


class DynamicTaskForm(forms.Form):
    """
    Dynamic form for tasks.
    Fields
        trash - store trash list from TrashModel
        file - store list files from trash
    """
    trash = forms.ModelChoiceField(queryset=TrashModel.objects.all())
    file = forms.ChoiceField()

trash/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import FormView
from django.http import JsonResponse
from trash.forms import CreateTrashForm, DynamicTaskForm, TaskForm
from trash.models import TrashModel, TrashModelTask
from json import loads


class CreateTrashView(FormView):
    """
    Class-based form processing view, which create trash by name,
    files_limit and size_limit form form fields.
    """
    form_class = CreateTrashForm
    success_url = '/'

    def form_valid(self, form):
        """
        Override action on not form.is_valid
        :param form: filled instance of form_class
        :return: form valid of super class
        """
        TrashModel.objects.create(
            name=form.data.get('name'),
            files_limit=form.data.get('files_limit'),
            size_limit=form.data.get('size_limit'),
        )
        return super(CreateTrashView, self).form_valid(form)


class RemoveFormView(FormView):
    """
    Class-based form processing view, which remove file from trash by
    trash name and trash file from form fields.
    """
    form_class = TaskForm
    success_url = '/tasks/'

    def form_valid(self, form):
        """
        Override action on form.is_valid
        :param form: filled instance of form_class
        :return: form_valid of super class
        """
        trash = get_object_or_404(TrashModel, pk=form.data.get('trash'))
        trash.remove(form.data.get('file'))
        return super(RemoveFormView, self).form_valid(form)


class RecoveryFormView(FormView):
    """
    Classed-based form processing view, which recover file from trash by
    trash and trash file from form fields.
    """
    form_class = TaskForm
    success_url = '/tasks/'

    def form_invalid(self, form):
        print form

    def form_valid(self, form):
        """
        Override action on form.is_valid
        :param form: filled instance of form_class
        :return: form_valid of super class
        """
        trash = get_object_or_404(TrashModel, pk=form.data.get('trash'))
        trash.recover(form.data.get('file'))
        return super(RecoveryFormView, self).form_valid(form)


def trash_list(request):
    """
    View trash list page
    :param request: django HttpRequest
    :return: page with trash list of trashes and trash menu
    """
    return render(request, 'trash_list.html', {
        'form': CreateTrashForm(),
        'trashes': TrashModel.objects.all(),
    })


def trash_content(request, trash_name):
    """
    View trash content page
    :param request: django HttpRequest
    :param trash_name: name of trash
    :return page with trash content page with trash files and trash menu
    """
    return render(request, 'trash_content.html', {
        'trash_name': trash_name,
        'content': get_object_or_404(TrashModel, name=trash_name).content()
    })


def tasks(request):
    """
    View task page
    :param request: django HttpRequest
    :return: page with task page with task history and task menu
    """
    return render(request, 'tasks.html', {
        'form': DynamicTaskForm(),
        'tasks': TrashModelTask.objects.all()
    })


def remove_ajax(request):
    """
    Remove from trash some list of files from ajax query
    :param request: django HttpRequest
    :return: json with ok or bad request status
    """
    if request.is_ajax() and request.method == 'POST':
        trash_name = request.POST.get('trash', None)
        files = loads(request.POST.get('files', '[]'))
        get_object_or_404(TrashModel, name=trash_name).remove_many(files)
        return JsonResponse({'status': 'method remove was called'})
    else:
        return JsonResponse({'status': 'bad request'})


def recover_ajax(request):
    """
    Recover from trash some list of files by ajax query
    :param request: django HttpRequest
    :return: json with ok or bad request status
    """
    if request.is_ajax() and request.method == 'POST':
        trash_name = request.POST.get('trash', None)
        files = loads(request.POST.get('files', '[]'))
        get_object_or_404(TrashModel, name=trash_name).recover_many(files)
        return JsonResponse({'status': 'method recover was called'})
    else:
        return JsonResponse({'status': 'bad request'})


def trash_content_ajax(request):
    """
    Get trash content by trash id by ajax query
    :param request: django HttpRequest
    :return: json status ok or bad request
    """
    if request.is_ajax() and request.method == 'POST':
        trash_name = request.POST.get('trash', None)
        trash = get_object_or_404(TrashModel, name=trash_name)
        return JsonResponse({
            'files': [name for name, size, date in trash.content()]
        })
    else:
        return JsonResponse({})

trash/templates/create_modal.html
{% extends 'modal.html' %}

{% block modal_id %}
    "createModal"
{% endblock %}

{% block modal_name %}
    Create trash
{% endblock %}

{% block modal_action %}
    {% url 'create_trash' %}
{% endblock %}

trash/templates/modal.html
{% load bootstrap3 %}

<div class="modal fade" role="dialog" id={% block modal_id %}{% endblock %}>
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">{% block modal_name %}{% endblock %}</h4>
            </div>

            <div class="modal-body">
                <form class="form"  method="post" action={% block modal_action %}{% endblock %}>
                    {% csrf_token %}

                    {% bootstrap_form form %}

                    {% buttons %}
                        <div class="text-right">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-default">Submit</button>
                        </div>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</div>

trash/templates/recover_modal.html
{% extends 'modal.html' %}

{% block modal_id %}
    "recoverModal"
{% endblock %}

{% block modal_name %}
    Recover files from trash
{% endblock %}

{% block modal_action %}
    {% url 'recover' %}
{% endblock %}

trash/templates/remove_modal.html
{% extends 'modal.html' %}

{% block modal_id %}
    "removeModal"
{% endblock %}

{% block modal_name %}
    Remove files from trash
{% endblock %}

{% block modal_action %}
    {% url 'remove' %}
{% endblock %}

trash/templates/tasks.html
{% extends 'base.html' %}

{% block left_menu %}
    <ul class="nav nav-pills nav-stacked well bg-success">
        <li class="active"><a href="">Overview history tasks</a></li>
        <li><a href="" data-toggle="modal" data-target="#removeModal">Remove files</a></li>
        <li><a href="" data-toggle="modal" data-target="#recoverModal">Recover files</a></li>
    </ul>
{% endblock %}

{% block content %}
    {% load staticfiles %}

    <script type="text/javascript" src="{% static 'js/dynamic_modal.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cookie_token.js' %}"></script>

    <table class="table table-striped">
        <tr>
            <th>Basket name</th>
            <th>Basket file</th>
            <th>Task</th>
            <th>Task status</th>
        </tr>

        {% for task in tasks %}
            <tr>
                <td class="col-xs-3">
                    <a href="{% url 'trash_content' trash_name=task.trash.name%}">{{ task.trash.name }}</a>
                </td>

                <td class="col-xs-3">{{ task.filename }}</td>
                <td class="col-xs-3">{{ task.get_operation_display }}</td>
                <td class="col-xs-3">{{ task.get_status_display }}</td>
            </tr>
        {% endfor %}
    </table>
    {% include 'remove_modal.html' %}
    {% include 'recover_modal.html' %}
{% endblock %}

trash/templates/trash_content.html
{% extends 'base.html' %}


{% block left_menu %}
    {% load staticfiles %}

    <script type="text/javascript" src="{% static 'js/ajax_tasks.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cookie_token.js' %}"></script>

    <ul class="nav nav-pills nav-stacked well bg-success">
        <li class="active"><a href="">Overview trash files</a></li>
        <li><a href="" id="removed">Remove files</a></li>
        <li><a href="" id="recovered">Recover files</a></li>
    </ul>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <th>Choose</th>
            <th>Filename</th>
            <th>File size</th>
            <th>File modify date</th>
        </tr>
        {% for file in content %}
            <tr>
                <td class="col-md-1"><input type="checkbox" class="file" name="{{ file.name }}"></td>
                <td class="col-md-4">{{ file.name }}</td>
                <td class="col-md-3">{{ file.size | filesizeformat}}</td>
                <td class="col-md-3">{{ file.modify | date}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

trash/templates/trash_list.html
{% extends 'base.html' %}

{% block left_menu %}
    <ul class="nav nav-pills nav-stacked well bg-success">
        <li class="active"><a href="{% url 'trash_list' %}">Overview trashes</a></li>
        <li><a href="" data-toggle="modal" data-target="#createModal">Create trash</a></li>
    </ul>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <tr>
            <th>Trash name</th>
            <th>Trash time of create</th>
            <th>Trash free size</th>
        </tr>
        {% for trash in trashes %}
            <tr>
                <td class="col-md-4">
                    <a href="{% url 'trash_content' trash_name=trash.name %}">{{ trash.name }}</a>
                </td>
                <td class="col-md-4">{{ trash.time_creation | date}}</td>
                <td class="col-md-4">{{ trash.instance.available_size_space | filesizeformat }}</td>
            </tr>
        {% endfor %}
    </table>
    {% include 'create_modal.html' %}
{% endblock %}